# Reviewers and Contributors {-}

We express our sincere gratitude to the researchers, students, and colleagues listed below for their essential work in evaluating, reviewing, and critically assessing the content of this book.

- **André Padial** - Department of Biological Sciences, Federal University of Paraná, Curitiba, Paraná, Brazil

- **Adriano Sanches Melo** - Institute of Biosciences, Federal University of Rio Grande do Sul (UFRGS), Vale Campus, Porto Alegre, Rio Grande do Sul, Brazil

- **Beatriz Milz** - Graduate Program in Environmental Science, Institute of Energy and Environment, University of São Paulo (PROCAM/IEE/USP), São Paulo, São Paulo, Brazil

- **Felipe Sodré Mendes Barros** - Department of Geography, Instituto Superior Antonio Ruiz de Montoya; Instituto Misionero de Biodiversidad (IMiBio); Ambiental Analytics, Misiones, Argentina

- **Ingrid da Silva Lima** - Graduate Program in Ethnobiology and Nature Conservation (PPGEtno), Federal Rural University of Pernambuco (UFRPE), Recife, Pernambuco, Brazil

- **Maurício Cetra** - Department of Environmental Sciences, Federal University of São Carlos (UFSCar), Sorocaba Campus, São Paulo, Brazil

- **Marcos Rafael Severgnini** - Graduate Program in Ecology and Conservation, Federal University of Mato Grosso do Sul, Campo Grande, Mato Grosso do Sul, Brazil

- **Marcos Robalinho Lima** - Department of Animal and Plant Biology, State University of Londrina, Londrina, Paraná, Brazil

- **Michel Varajão Garey** - Latin American Institute of Life and Nature Sciences (ILACVN), Federal University for Latin American Integration (UNILA), Foz do Iguaçu, Paraná, Brazil

- **Paulo Mateus Martins Sobrinho** - Graduate Program in Ethnobiology and Nature Conservation (PPGEtno), Federal Rural University of Pernambuco (UFRPE), Recife, Pernambuco, Brazil

- **Paulo Sérgio Monteiro Ferreira** - State Department of Education of Paraíba, Paraíba, Brazil

- **Pedro Henrique Albuquerque Sena** - Northeast Environmental Research Center (Cepan), Recife, Pernambuco, Brazil

- **Reginaldo Augusto Farias de Gusmão** - Graduate Program in Ethnobiology and Nature Conservation (PPGEtno), Federal Rural University of Pernambuco (UFRPE), Recife, Pernambuco, Brazil

- **Victor Satoru Saito** - Department of Environmental Sciences, Federal University of São Carlos (UFSCar), São Carlos Campus, São Paulo, Brazil